# Generated by Django 5.0.4 on 2024-07-23 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_index', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_title', models.CharField(blank=True, max_length=100)),
                ('bump_timestamp', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
                ('sticky', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_no', models.IntegerField(default=0)),
                ('post_body', models.CharField(max_length=800)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_last_modified', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.thread')),
            ],
            options={
                'ordering': ['post_no'],
            },
        ),
    ]
