# Generated by Django 4.2.9 on 2024-01-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
